version: "3.4"
services:
  server:
    hostname: server
    build:
      context: .
      target: server
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - .:/srv
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # frontend:
  #   hostname: frontend
  #   privileged: true
  #   ports:
  #     - 8000:80
  #   build:
  #     context: .
  #     target: frontend
  #   tmpfs:
  #     - /tmp
  #     - /run
  #     - /run/lock
  #   volumes:
  #     - .:/srv
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
      
  # node1:
  #   hostname: node1
  #   privileged: true
  #   build:
  #     context: .
  #     target: node
  #   tmpfs:
  #     - /tmp
  #     - /run
  #     - /run/lock
  #   volumes:
  #     - .:/srv
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro    
  # node2:
  #   hostname: node2
  #   privileged: true
  #   build:
  #     context: .
  #     target: node
  #   tmpfs:
  #     - /tmp
  #     - /run
  #     - /run/lock
  #   volumes:
  #     - .:/srv
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro

